# Netty-specific options.
netty:

  # Port to listen on for new events
  listenPort: 4433

  # Maximum line length
  maxLength: 100KB

  ssl: true
  selfSignedCert: false
  clientAuth: true
  keyCertChainFile: scripts/server.crt
  keyFile: scripts/server_pkcs8.key
  #keyPassword: changeit
  trustCertCollectionFile: scripts/ca.crt

  filters:
    accept:
      - 127.0.0.1

# AWS-specific options.
aws:
  bucketName: smoketurner-uploads
  prefix: events

  # Maximum upload size
  maxUploadSize: 10MB

# HTTP-specific options.
server:
  type: simple
  minThreads: 1
  applicationContextPath: /
  connector:
    type: http
    port: 8080
    acceptorThreads: 1
    selectorThreads: 1

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

logging:
  level: INFO
  loggers:
    com.smoketurner.uploader: DEBUG
    io.netty: INFO
    com.amazonaws.services.s3.transfer: DEBUG
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
