# Netty-specific options.
netty:

  # Port to listen on for new events
  listenPort: ${PORT:-4433}

  # Maximum line length
  maxLength: 100KB

  ssl: true
  selfSignedCert: false
  clientAuth: true
  keyCertChainFile: scripts/server.crt
  keyFile: scripts/server_pkcs8.key
  #keyPassword: changeit
  trustCertCollectionFile: scripts/ca.crt

  filters:
    accept:
      - 127.0.0.1

# AWS-specific options.
aws:
  bucketName: smoketurner-uploads
  region: us-east-1
  prefix: events

  # Maximum upload size
  maxUploadSize: 10MB

# HTTP-specific options.
server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: scripts/keystore.jks
      keyStorePassword: changeit
      trustStorePath: scripts/truststore.jks
      trustStorePassword: changeit
      needClientAuth: true
      # see https://github.com/dropwizard/dropwizard/issues/1710
      validateCerts: false
      validatePeers: true
      allowRenegotiation: false
      # needed to support curl
      excludedCipherSuites:
        - SSL_RSA_WITH_DES_CBC_SHA
        - SSL_DHE_RSA_WITH_DES_CBC_SHA
        - SSL_DHE_DSS_WITH_DES_CBC_SHA
        - SSL_RSA_EXPORT_WITH_RC4_40_MD5
        - SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
        - SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
        - SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
  adminConnectors:
    - type: http
      port: 8180

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

logging:
  level: INFO
  loggers:
    com.smoketurner.uploader: DEBUG
    io.netty: INFO
    com.amazonaws.services.s3.transfer: DEBUG
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
